services:
  activemq:
    image: symptoma/activemq:latest
    container_name: activemq-artemis
    ports:
      - "61613:61613" # Default port for the OpenWire protocol
      - "61614:61614" # Default port for the Stomp
      - "61616:61616" # Default port for the OpenWire protocol
      - "8161:8161"   # Web console
      - "1883:1883"
      - "5672:5672"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_NAME: localhost
    volumes:
      - activemq_data:/data
      - activemq_logs:/var/log/activemq

volumes:
  activemq_data:
  activemq_logs: