name: Deploy AMQ Infra
on:
  workflow_dispatch:
#  push:
#    branches:
#      - 2.1-two-queues-amz-mq

jobs:
  amq-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: provision infra
        uses: cham207388/github-custom-actions/terraform@main
        with:
          directory: ./terraform
          aws-region: us-east-2
          variables: "region=us-east-2,amq_username=${{ secrets.AMQ_USERNAME }},amq_password=${{ secrets.AMQ_PASSWORD }},subnet_id=${{ secrets.SUBNET_ID_1}}"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

