name: Deploy with Custom Actions
on:
  workflow_dispatch:

jobs:
  docker-and-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: 1 - Checkout code
        uses: actions/checkout@v4

      - name: 4 - Provision EKS Cluster
        uses: cham207388/github-custom-actions/terraform@main
        with:
          directory: ./terraform
          aws-region: us-east-2
          variables: "region=us-east-2,amq_username=${{ secrets.AMQ_USERNAME }},amq_password=${{ secrets.AMQ_USERNAME }},subnet_id=${{ secrets.SUBNET_ID_1}}"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

